Repository 401n1-midterm/penny-pincher, pull requests merged in 2020-08, with the labels that each got.

#3 readme updated
  README.md
  Requirements.md
  assets/routing_diagram.png
  assets/sample_ERD.png
  assets/wireframe_1.png
  assets/wireframe_2.png
  docs/requirements.md
  docs/workflow.md
  poetry.lock
  pyproject.toml
  ticket_search/functions.py
  ticket_search/views.py
Labels: documentation

#5 Dev
  README.md
  Requirements.md
  assets/routing_diagram.png
  assets/sample_ERD.png
  assets/wireframe_1.png
  assets/wireframe_2.png
  docs/requirements.md
  docs/workflow.md
  manage.py
  penny_pincher/__init__.py
  penny_pincher/asgi.py
  penny_pincher/settings.py
  penny_pincher/urls.py
  penny_pincher/wsgi.py
  poetry.lock
  pyproject.toml
  templates/base.html
  templates/partials/_alerts.html
  templates/partials/_footer.html
  templates/partials/_navbar.html
  templates/ticket_search/about.html
  templates/ticket_search/home.html
  ticket_search/__init__.py
  ticket_search/admin.py
  ticket_search/apps.py
  ticket_search/functions.py
  ticket_search/migrations/__init__.py
  ticket_search/models.py
  ticket_search/tests.py
  ticket_search/urls.py
  ticket_search/views.py
Labels: documentation

#6 Search
  .gitignore
  penny_pincher/settings.py
  templates/partials/_navbar.html
  templates/ticket_search/search.html
  ticket_search/functions.py
  ticket_search/static/js/main.js
  ticket_search/urls.py
  ticket_search/views.py
Labels: new feature

#7 Database
  .gitignore
  penny_pincher/settings.py
  poetry.lock
  pyproject.toml
  templates/ticket_search/results.html
  templates/ticket_search/search.html
  ticket_search/admin.py
  ticket_search/forms.py
  ticket_search/migrations/0001_initial.py
  ticket_search/migrations/0002_auto_20200808_1815.py
  ticket_search/models.py
  ticket_search/urls.py
  ticket_search/views.py
Labels: new feature

#8 Form validation
  penny_pincher/settings.py
  poetry.lock
  pyproject.toml
  templates/ticket_search/search.html
  ticket_search/forms.py
  ticket_search/static/css/style.css
  ticket_search/static/js/test.js
  ticket_search/views.py
Labels: enhancement, new feature

#9 Dev
  .gitignore
  penny_pincher/settings.py
  poetry.lock
  pyproject.toml
  templates/partials/_navbar.html
  templates/ticket_search/results.html
  templates/ticket_search/search.html
  ticket_search/admin.py
  ticket_search/forms.py
  ticket_search/functions.py
  ticket_search/migrations/0001_initial.py
  ticket_search/migrations/0002_auto_20200808_1815.py
  ticket_search/models.py
  ticket_search/static/css/style.css
  ticket_search/static/js/main.js
  ticket_search/static/js/test.js
  ticket_search/urls.py
  ticket_search/views.py
Labels: enhancement, new feature

#10 Merge master into dev (required due to deployment)
  .github/workflows/github_actions.yml
  .gitignore
  Procfile
  README.md
  penny_pincher/settings.py
  poetry.lock
  pyproject.toml
  requirements.txt
  runtime.txt
  templates/ticket_search/home.html
  templates/ticket_search/results.html
  templates/ticket_search/search.html
  ticket_search/functions.py
  ticket_search/migrations/0001_initial.py
  ticket_search/migrations/0002_auto_20200808_1815.py
  ticket_search/views.py
Labels: new feature

#12 jQuery modal with Bootstrap
  templates/ticket_search/search.html
  ticket_search/static/img/plane_icon.png
  ticket_search/static/js/test.js
Labels: enhancement, new feature

#13 Merging Dev into Master
  penny_pincher/settings.py
  templates/ticket_search/search.html
  ticket_search/static/img/plane_icon.png
  ticket_search/static/js/test.js
  ticket_search/tests.py
Labels: new feature, test

#14 Merging master into dev
  penny_pincher/settings.py
Labels: bugfix

#15 Registration
  penny_pincher/settings.py
  penny_pincher/urls.py
  templates/base.html
  templates/partials/_navbar.html
  templates/users/login.html
  templates/users/logout.html
  templates/users/profile.html
  templates/users/register.html
  ticket_search/migrations/0001_initial.py
  ticket_search/urls.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/forms.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: new feature

#16 Merging dev into the master
  penny_pincher/settings.py
  penny_pincher/urls.py
  templates/base.html
  templates/partials/_navbar.html
  templates/users/login.html
  templates/users/logout.html
  templates/users/profile.html
  templates/users/register.html
  ticket_search/migrations/0001_initial.py
  ticket_search/urls.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/forms.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: bug, new feature

#17 Selenium functionality extended
  templates/ticket_search/results.html
  templates/ticket_search/search.html
  ticket_search/forms.py
  ticket_search/functions.py
  ticket_search/tests.py
  ticket_search/views.py
Labels: new feature

#19 added tests for users routes
  ticket_search/tests.py
Labels: test

#20 working on form date validation
  ticket_search/static/js/search_wait.js
Labels: enhancement

#23 merging master into dev
  .github/workflows/github_actions.yml
  Procfile
  penny_pincher/settings.py
  poetry.lock
  pyproject.toml
  requirements.txt
  runtime.txt
  templates/partials/_navbar.html
  templates/ticket_search/history.html
  templates/ticket_search/results.html
  templates/ticket_search/search.html
  templates/ticket_search/wait.html
  ticket_search/apps.py
  ticket_search/forms.py
  ticket_search/functions.py
  ticket_search/migrations/0001_initial.py
  ticket_search/models.py
  ticket_search/static/css/gijgo.min.css
  ticket_search/static/js/gijgo.min.js
  ticket_search/static/js/search_wait.js
  ticket_search/static/js/wait.js
  ticket_search/tests.py
  ticket_search/urls.py
  ticket_search/views.py
Labels: new feature, test

#22 set-up-welcome-about
  templates/partials/_navbar.html
  templates/ticket_search/about.html
  templates/ticket_search/home.html
  ticket_search/static/css/about.css
  ticket_search/static/css/home.css
  ticket_search/static/img/home-background.jpg
Labels: enhancement

#25 History page edited
  README.md
  assets/ERD.png
  assets/sample_ERD.png
  penny_pincher/settings.py
  templates/base.html
  templates/partials/_footer.html
  templates/partials/_navbar.html
  templates/ticket_search/about.html
  templates/ticket_search/history.html
  templates/ticket_search/home.html
  templates/ticket_search/results.html
  templates/ticket_search/search.html
  templates/ticket_search/wait.html
  templates/users/login.html
  templates/users/logout.html
  templates/users/profile.html
  templates/users/register.html
  templates/welome.html
  ticket_search/migrations/0001_initial.py
  ticket_search/migrations/0002_auto_20200815_2337.py
  ticket_search/migrations/0003_auto_20200815_2338.py
  ticket_search/models.py
  ticket_search/static/css/home.css
  ticket_search/static/css/style.css
  ticket_search/static/img/home-background.jpg
  ticket_search/static/img/leo-500x500.jpg
  ticket_search/static/js/history.js
  ticket_search/static/js/search_wait.js
  ticket_search/views.py
Labels: enhancement, new feature

#24 Styling
  README.md
  assets/ERD.png
  assets/sample_ERD.png
  penny_pincher/settings.py
  templates/base.html
  templates/partials/_footer.html
  templates/partials/_navbar.html
  templates/ticket_search/about.html
  templates/ticket_search/history.html
  templates/ticket_search/home.html
  templates/ticket_search/results.html
  templates/ticket_search/search.html
  templates/ticket_search/wait.html
  templates/users/login.html
  templates/users/logout.html
  templates/users/profile.html
  templates/users/register.html
  templates/welome.html
  ticket_search/static/css/about.css
  ticket_search/static/css/home.css
  ticket_search/static/css/style.css
  ticket_search/static/img/home-background.jpg
  ticket_search/static/img/leo-500x500.jpg
  ticket_search/static/js/search_wait.js
  ticket_search/views.py
Labels: enhancement

#27 Style fix
  penny_pincher/settings.py
  templates/ticket_search/history.html
  templates/ticket_search/home.html
  templates/users/login.html
  templates/users/logout.html
  templates/users/profile.html
  ticket_search/migrations/0002_auto_20200815_2337.py
  ticket_search/migrations/0003_auto_20200815_2338.py
  ticket_search/models.py
  ticket_search/static/css/style.css
  ticket_search/static/js/history.js
  ticket_search/views.py
  users/views.py
Labels: bugfix

#28 Merging new styles dev into master
  penny_pincher/settings.py
  templates/ticket_search/history.html
  templates/ticket_search/home.html
  templates/users/login.html
  templates/users/logout.html
  templates/users/profile.html
  ticket_search/static/css/style.css
  ticket_search/static/js/history.js
  users/views.py
Labels: bugfix

#30 Style fix
  templates/base.html
  templates/ticket_search/about.html
  templates/ticket_search/history.html
  templates/ticket_search/home.html
  templates/ticket_search/results.html
  templates/ticket_search/search.html
  templates/ticket_search/wait.html
  templates/users/login.html
  templates/users/profile.html
  templates/users/register.html
  ticket_search/forms.py
  ticket_search/static/js/history.js
  ticket_search/static/js/main.js
  ticket_search/static/js/search.js
  ticket_search/static/js/search_wait.js
  ticket_search/urls.py
  ticket_search/views.py
Labels: new feature

#31 Dev
  templates/base.html
  templates/ticket_search/about.html
  templates/ticket_search/history.html
  templates/ticket_search/home.html
  templates/ticket_search/results.html
  templates/ticket_search/search.html
  templates/ticket_search/wait.html
  templates/users/login.html
  templates/users/profile.html
  templates/users/register.html
  ticket_search/forms.py
  ticket_search/static/js/history.js
  ticket_search/static/js/main.js
  ticket_search/static/js/search.js
  ticket_search/static/js/search_wait.js
  ticket_search/urls.py
  ticket_search/views.py
Labels: enhancement

#33 Search results
  ticket_search/functions.py
  ticket_search/views.py
Labels: enhancement, new feature

#34 Dependency change
  Procfile
  penny_pincher/settings.py
  poetry.lock
  pyproject.toml
  requirements.txt
  templates/ticket_search/history.html
  templates/ticket_search/wait.html
  ticket_search/forms.py
  ticket_search/functions.py
  ticket_search/migrations/0004_searchquery_error.py
  ticket_search/models.py
  ticket_search/static/js/wait.js
  ticket_search/views.py
Labels: bugfix

#35 Merging dev into master
  Procfile
  penny_pincher/settings.py
  poetry.lock
  pyproject.toml
  requirements.txt
  templates/ticket_search/history.html
  templates/ticket_search/wait.html
  ticket_search/forms.py
  ticket_search/functions.py
  ticket_search/migrations/0004_searchquery_error.py
  ticket_search/models.py
  ticket_search/static/js/wait.js
  ticket_search/views.py
Labels: bugfix

#37 about me done
  templates/ticket_search/about.html
  ticket_search/static/img/chuck.jpg
Labels: documentation

#40 Merging dev into master
  README.md
  poetry.lock
  pyproject.toml
  requirements.txt
  templates/ticket_search/about.html
  templates/ticket_search/history.html
  templates/ticket_search/home.html
  templates/ticket_search/results.html
  templates/ticket_search/search.html
  templates/ticket_search/wait.html
  ticket_search/forms.py
  ticket_search/functions.py
  ticket_search/migrations/0005_auto_20200819_2120.py
  ticket_search/migrations/0006_auto_20200819_2142.py
  ticket_search/models.py
  ticket_search/static/css/wait.css
  ticket_search/static/img/chuck.jpg
  ticket_search/static/img/joe.jpeg
  ticket_search/static/img/plane_icon.png
  ticket_search/static/js/results.js
  ticket_search/static/js/wait.js
  ticket_search/urls.py
  ticket_search/views.py
Labels: enhancement
